"""Design2Code environment - manages HTML generation tasks from screenshots."""

import os
import base64
import tempfile
from pathlib import Path
from typing import Optional
from dataclasses import dataclass

# Import evaluation module
from src.evaluation import VisualEvaluator


@dataclass
class Design2CodeTask:
    """Represents a single Design2Code task with screenshot and reference HTML."""
    task_id: int
    screenshot_path: str
    reference_html_path: str
    screenshot_base64: Optional[str] = None
    reference_html: Optional[str] = None


@dataclass
class EnvResetResult:
    """Result from environment reset operation."""
    observation: str
    info: dict


@dataclass
class EnvStepResult:
    """Result from environment step operation."""
    observation: str
    reward: float
    done: bool
    info: dict


class Design2CodeEnvironment:
    """Environment for evaluating HTML generation from screenshots."""

    def __init__(self, data_folder: str, task_ids: list[int]):
        """
        Initialize the Design2Code environment.

        Args:
            data_folder: Path to folder containing HTML files and screenshots
            task_ids: List of task IDs to load (e.g., [2, 6, 7, 11] for 2.html, 6.html, etc.)
        """
        self.data_folder = Path(data_folder)
        self.task_ids = task_ids
        self.tasks: dict[int, Design2CodeTask] = {}
        self.current_task: Optional[Design2CodeTask] = None
        self.generated_html: Optional[str] = None

        # Initialize visual evaluator
        self.evaluator = VisualEvaluator(
            min_similarity_threshold=0.5,
            consecutive_bonus=0.1,
            window_size=1
        )

        # Load all tasks
        self._load_tasks()

    def _load_tasks(self):
        """Load HTML and screenshot files for all task IDs."""
        for task_id in self.task_ids:
            html_path = self.data_folder / f"{task_id}.html"
            screenshot_path = self.data_folder / f"{task_id}.png"

            # Check if files exist
            if not html_path.exists():
                print(f"Warning: HTML file not found: {html_path}")
                continue
            if not screenshot_path.exists():
                print(f"Warning: Screenshot not found: {screenshot_path}")
                continue

            # Create task object
            task = Design2CodeTask(
                task_id=task_id,
                screenshot_path=str(screenshot_path),
                reference_html_path=str(html_path)
            )

            # Load reference HTML
            with open(html_path, 'r', encoding='utf-8') as f:
                task.reference_html = f.read()

            # Load and encode screenshot as base64
            with open(screenshot_path, 'rb') as f:
                screenshot_bytes = f.read()
                task.screenshot_base64 = base64.b64encode(screenshot_bytes).decode('utf-8')

            self.tasks[task_id] = task
            print(f"Loaded task {task_id}: {html_path.name} and {screenshot_path.name}")

    def reset(self, task_id: int) -> EnvResetResult:
        """
        Reset environment to a specific task.

        Args:
            task_id: ID of the task to load

        Returns:
            EnvResetResult with observation and info
        """
        if task_id not in self.tasks:
            raise ValueError(f"Task {task_id} not found in loaded tasks: {list(self.tasks.keys())}")

        self.current_task = self.tasks[task_id]
        self.generated_html = None

        # Create observation with screenshot data
        screenshot_preview = self.current_task.screenshot_base64[:100] if self.current_task.screenshot_base64 else ""
        observation = f"""Task: Generate HTML code that matches the provided screenshot.

The screenshot is provided as a base64-encoded PNG image.
Please analyze the screenshot and generate the HTML code that would produce a similar visual result.

Screenshot (base64): {screenshot_preview}... (truncated, full data available)

Please provide your HTML code wrapped in <html_code>...</html_code> tags.
"""

        info = {
            "task_id": task_id,
            "screenshot_path": self.current_task.screenshot_path,
            "reference_html_path": self.current_task.reference_html_path,
        }

        return EnvResetResult(observation=observation, info=info)

    def step(self, html_code: str) -> EnvStepResult:
        """
        Process the generated HTML code and evaluate it using Design2Code metrics.

        Args:
            html_code: The HTML code generated by the agent

        Returns:
            EnvStepResult with observation, reward, done flag, and info
        """
        if self.current_task is None:
            raise ValueError("Environment not reset. Call reset() first.")

        self.generated_html = html_code

        # Save generated HTML to temporary file
        with tempfile.NamedTemporaryFile(
            mode='w',
            suffix='.html',
            delete=False,
            encoding='utf-8'
        ) as f:
            f.write(html_code)
            gen_html_path = f.name

        try:
            # Use visual evaluator to calculate reward
            result = self.evaluator.evaluate(
                ref_html_path=self.current_task.reference_html_path,
                gen_html_path=gen_html_path,
                ref_screenshot_path=self.current_task.screenshot_path,
                gen_screenshot_path=None  # Will be auto-generated
            )

            # Reward is the overall score from evaluation
            reward = result.overall_score

            observation = f"""HTML code evaluated using Design2Code metrics:
- Block Match: {result.block_match_score:.3f}
- Text Similarity: {result.text_score:.3f}
- Position Similarity: {result.position_score:.3f}
- Color Similarity: {result.color_score:.3f}
- CLIP Score: {result.clip_score:.3f}
Overall Score: {result.overall_score:.3f}
"""

            done = True  # Task is complete after one submission

            info = {
                "task_id": self.current_task.task_id,
                "generated_html_length": len(html_code),
                "reference_html_length": len(self.current_task.reference_html or ""),
                "reward": reward,
                "block_match_score": result.block_match_score,
                "text_score": result.text_score,
                "position_score": result.position_score,
                "color_score": result.color_score,
                "clip_score": result.clip_score,
                "matched_pairs": result.matched_pairs,
                "total_ref_blocks": result.total_ref_blocks,
                "total_gen_blocks": result.total_gen_blocks,
            }

        finally:
            # Clean up temporary file
            if os.path.exists(gen_html_path):
                os.unlink(gen_html_path)

        return EnvStepResult(
            observation=observation,
            reward=reward,
            done=done,
            info=info
        )

    def get_wiki(self) -> str:
        """
        Get the task instruction/wiki for the environment.

        Returns:
            Instruction text for the agent
        """
        return """You are an HTML generation expert. Your task is to generate HTML code from screenshots.

Given a screenshot of a webpage, you need to:
1. Analyze the visual layout, colors, text, and styling
2. Generate HTML and CSS code that recreates the visual appearance
3. Ensure proper HTML structure with <!DOCTYPE>, <html>, <head>, and <body> tags
4. Include inline styles or <style> tags for CSS

Provide your response wrapped in <html_code>...</html_code> tags.
"""

    def get_reference_html(self) -> Optional[str]:
        """
        Get the reference HTML for the current task.

        Returns:
            Reference HTML code or None if no task is loaded
        """
        if self.current_task is None:
            return None
        return self.current_task.reference_html
